### ISSUE TITLE
OL and AHC not saving to event

### ISSUE THREAD

**Issue by cody-barkley** [BAMRU-Tech/bamru_net#484]
When assigning OL or AHC, functionality appears normal.  But when you leave the event page and come back, the AHC and OL designation are not there.  It's as if they are not saving beyond the initial action.  Not critical.   Error occurs on Safari and Firefox

**Comment by kduncklee** [comment]
Sorry about this, it's due to the new google account not being enabled on prod yet and I didn't properly test that case.

Fix is submitted in cb1068b06d374be9e8e760ce2d254ced9bd2e7a1 but not merged to master yet.

**Comment by kduncklee** [comment]
This actually appears to be due to the multi-select editor change.

I think it is due to RowEditHandler not setting the ol or ahc fields. Setting OL and reloading the page clears the OL bit. Setting the OL and then editing again makes it stick. In the first edit, the request has ol=false, the second has ol=true.
