### ISSUE TITLE
CSV Roster does not include BAMRU.org email addresses

### ISSUE THREAD

**Issue by scot** [BAMRU-Tech/bamru_net#627]
On the [Reports page](https://bamru.net/reports/), the [CSV export](https://bamru.net/reports/roster/BAMRU-roster.csv) includes all email addresses except for each team member's @bamru.org address. 

This is problematic for any time we need to get our Roster, including for submitting it and the required email addresses to the MRA for annual membership. Currently this requires a manual step, which could be prone to error.

**Comment by tyeh26** [comment]
Agreed that this is problematic.

Follow up question, does the CSV Roster need non-@bamru.org email addresses at all?  It's a very simple change to remove all, other, email addresses and only include the @bamru.org email address.

It's a tiny bit more involved to maintain work/personal/home(?!?) email addresses and adding the official team email address because I would re-label all team email address from "Other" to "Team".  See attached screenshot. and attached branch for example of the "easy" change.
<img width="447" alt="Screenshot 2023-12-15 at 11 42 31 AM" src="https://github.com/BAMRU-Tech/bamru_net/assets/141905/c0b2e103-6adf-494d-acbb-27a2bc29c8c7">

**Comment by scot** [comment]
Personally, I like the idea of labeling it as Team. As of now, I think including only Team addresses in CSV is sufficient (we can use the other exports for filling our Contacts apps)

**Comment by tyeh26** [comment]
PR made and [Issue 657](https://github.com/BAMRU-Tech/bamru_net/issues/657) made to introduce a Team label.
